services:
    _defaults:
        autowire: true
        autoconfigure: true

    IWD\SymfonyDoctrineSearch\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DependencyInjection/'

    IWD\SymfonyDoctrineSearch\Service\RequestParser\Interfaces\BaseFilterStrategyMakerInterface:
        class: IWD\SymfonyDoctrineSearch\Service\RequestParser\Implementations\BaseFilterStrategyMaker

    IWD\SymfonyDoctrineSearch\Service\RequestParser\Interfaces\FiltersMakerInterface:
        class: IWD\SymfonyDoctrineSearch\Service\RequestParser\Implementations\FiltersMaker

    IWD\SymfonyDoctrineSearch\Service\RequestParser\Interfaces\PaginationMakerInterface:
        class: IWD\SymfonyDoctrineSearch\Service\RequestParser\Implementations\PaginationMaker

    IWD\SymfonyDoctrineSearch\Service\RequestParser\Interfaces\SortsMakerInterface:
        class: IWD\SymfonyDoctrineSearch\Service\RequestParser\Implementations\SortsMaker

    IWD\SymfonyDoctrineSearch\Service\RequestParser\Interfaces\RequestParserInterface:
        class: IWD\SymfonyDoctrineSearch\Service\RequestParser\Implementations\RequestParser
